apiVersion: v1
kind: Service
metadata:
  name: camera-simulator-service
spec:
  # This tells K8s to expose this outside the cluster
  type: LoadBalancer
  selector:
    # This must match the label in your deployment exactly
    app: cctv-sim
  ports:
    - name: web-ui
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: rtsp-video
      port: 8554
      targetPort: 8554