name: DevSecOps Security Gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-security:
    name: Build & Scan Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # We build the image locally in the CI runner first, but do not push it anywhere yet.
      - name: Build Simulator Image
        run: docker build -t cctv-simulator:ci-test ./src-camera-simulator

      # We unleash Trivy to scan the image layers and Python dependencies.
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cctv-simulator:ci-test'
          format: 'table'
          # CRITICAL: exit-code '1' tells GitHub to fail the pipeline if a vulnerability is found.
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
