name: Enterprise Infrastructure Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  validate-terraform:
    name: Security & Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./env-local-docker
        run: terraform init -backend=false

      - name: Terraform Format Check
        working-directory: ./env-local-docker
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./env-local-docker
        run: terraform validate
